### PR TITLE
Hotfix/vuv

### LINKED ISSUE #1291: Potential multigrid regression due to two-stage tuning
While trying to understand the regression reported #1287 I have found a potentially related regression that I don't understand.  This was introduced as part of the two-stage tuning (#1260).  This regression concerns the VUV kernel, and it is ~33% slower with the two-stage tuning.  What is especially perplexing is that the regression isn't apparent in the first sweep to find the candidates, it seems to appear in the second stage of the tuning.

E.g., VUV kernel, half precision, 16^4 volume, 4^4 blocking on a Quadro GV100 (prior to #1260) reports performance around ~1800-1900 GFLOPS.  This performance is observed in the first stage of autotuning:
```
MG level 0 (GPU): About to call tunable.apply block=(128,1,1) grid=(256,2,4) shared_bytes=16384 aux=(2,1,1)
MG level 0 (GPU): C   block=(128,1,1), grid=(256,2,4), shared_bytes=16384, aux=(2,1,1,1) gives 1833.42 Gflop/s, 923.87 GB/s
MG level 0 (GPU): About to call tunable.apply block=(128,1,1) grid=(256,2,4) shared_bytes=16385 aux=(2,1,1)
MG level 0 (GPU): C   block=(128,1,1), grid=(256,2,4), shared_bytes=16385, aux=(2,1,1,1) gives 1835.08 Gflop/s, 924.71 GB/s
```
However, when these are re-run in the second step, the kernels are significantly slower
```
MG level 0 (GPU): About to call tunable.apply block=(128,1,1) grid=(256,2,4) shared_bytes=16384 aux=(2,1,1)
MG level 0 (GPU): T   block=(128,1,1), grid=(256,2,4), shared_bytes=16384, aux=(2,1,1,1) gives 1292.92 Gflop/s, 651.51 GB/s
MG level 0 (GPU): About to call tunable.apply block=(128,1,1) grid=(256,2,4) shared_bytes=16385 aux=(2,1,1)
MG level 0 (GPU): T   block=(128,1,1), grid=(256,2,4), shared_bytes=16385, aux=(2,1,1,1) gives 1288.45 Gflop/s, 649.26 GB/s
```

I don't understand how this can be happening.  If anything, the increased iteration count in the second step of tuning should lead to faster performance since there is less host induced latency.

@mathiaswagner thoughts?

### PR DESCRIPTION
**Pull request by maddyscientist**
This hotfix fixes the performance of the VUV kernel:
* When two-stage tuning was enabled, it was observed that the VUV kernel seemingly regressed (#1291)
* It turns out this wasn't a regression per se, rather it revealed a long standing issue that the launch parameters of the VUV kernel weren't being set correctly outside of the tuning loop
* Specifically, the `Arg::coarse_color_wave` parameter, which maps to `TuneParam::aux` wasn't being set in the `apply` function, it was only being set during the tuning process.
* So while the kernel autotuned correctly, post tuning, it would not be using the desired parameters, leading to reduced performance.

I have also made some minor changes to the tuning:
* Display a warning if the best second-stage tuning time regresses by more than 10% versus the first stage.  In general we should expect the second stage to be faster than the first stage, since it will generally involve more iterations.  The 10% margin is left due to latency bubbles, etc.
* Even then, this warning can still be triggered if one doesn't lock clocks for small short running kernels.
* Fix a minor bug when printing the `aux` parameter while tuning.
* Replace use of `new`/`delete` with a `std::vector`

Closes #1291

### CODE REVIEW

**Comment by weinbe2** [comment]
Visual review looks great, I'm always a fan of a simple fix. I've got a due-diligence build+run going now, once that's complete I'll give it the approval + merge.

**Review by weinbe2 — APPROVED** [review]
This passes a range of (staggered) perf and correctness checks, so I'll consider this good---thanks for the fix @maddyscientist !

File: lib/tune.cpp [hunk 1]
```diff
@@ -966,13 +964,14 @@ namespace quda
...
-            printfQuda("About to call tunable.apply block=(%d,%d,%d) grid=(%d,%d,%d) shared_bytes=%d aux=(%d,%d,%d)\n",
+            printfQuda("About to call tunable.apply block=(%d,%d,%d) grid=(%d,%d,%d) shared_bytes=%d aux=(%d,%d,%d,%d)\n",
                        static_cast<int>(param.block.x), static_cast<int>(param.block.y),
                        static_cast<int>(param.block.z), static_cast<int>(param.grid.x), static_cast<int>(param.grid.y),
                        static_cast<int>(param.grid.z), static_cast<int>(param.shared_bytes),
-                       static_cast<int>(param.aux.x), static_cast<int>(param.aux.y), static_cast<int>(param.aux.z));
+                       static_cast<int>(param.aux.x), static_cast<int>(param.aux.y), static_cast<int>(param.aux.z), static_cast<int>(param.aux.w));
           }
 
+          tunable.apply(stream);
```
Comment (mathiaswagner) [inline lib/tune.cpp:974]: why is this needed?

Comment (maddyscientist) [reply lib/tune.cpp:974]: I made a comment on this in [c8a53f7](https://github.com/lattice/quda/pull/1292/commits/c8a53f7d6482cf91ad39b1a1dcf99047cccab7a1).  Without this warmup call, even with locked clocks there were some warnings about second-stage regressions.  This additional call costs nothing, but made the warnings go away.

Comment (mathiaswagner) [reply lib/tune.cpp:974]: might be worth adding a comment in the code as well.

Comment (maddyscientist) [reply lib/tune.cpp:974]: Fair point.  I'll add it in my next PR, whatever that may be....

Comment (maddyscientist) [reply lib/tune.cpp:974]: Hopefully one that fixes #1287.....
