### PR TITLE
Fixes for Fermi multi-GPU with texture references

### LINKED ISSUE #685: Fermi Dslash error
Hi, 
I'm getting that error, when I call the Wilson Dslash: 
```
PreTune N4quda16WilsonDslashCudaI7double2S1_EE
Tuning N4quda16WilsonDslashCudaI7double2S1_EE with policy,comm=0000,reconstruct=12,Xpay,topo=1111 at vol=6x12x12x4
About to call tunable.apply block=(32,1,1) grid=(1,1,1) shared_bytes=0 aux=(0,0,0)
    block=(32,1,1), shared=0, aux=(0,0,0,0) gives 38.31 Gflop/s, 64.53 GB/s
About to call tunable.apply block=(32,1,1) grid=(1,1,1) shared_bytes=0 aux=(1,0,0)
    block=(32,1,1), shared=0, aux=(1,0,0,0) gives 38.45 Gflop/s, 64.77 GB/s
About to call tunable.apply block=(32,1,1) grid=(1,1,1) shared_bytes=0 aux=(6,0,0)
    block=(32,1,1), shared=0, aux=(6,0,0,0) gives 38.37 Gflop/s, 64.62 GB/s
About to call tunable.apply block=(32,1,1) grid=(1,1,1) shared_bytes=0 aux=(7,0,0)
    block=(32,1,1), shared=0, aux=(7,0,0,0) gives 38.40 Gflop/s, 64.68 GB/s
About to call tunable.apply block=(32,1,1) grid=(1,1,1) shared_bytes=0 aux=(8,0,0)
    block=(32,1,1), shared=0, aux=(8,0,0,0) gives 38.36 Gflop/s, 64.60 GB/s
About to call tunable.apply block=(32,1,1) grid=(1,1,1) shared_bytes=0 aux=(9,0,0)
    block=(32,1,1), shared=0, aux=(9,0,0,0) gives 38.43 Gflop/s, 64.73 GB/s
Tuned block=(32,1,1), shared=0, aux=(1,0,0,0) giving 38.45 Gflop/s, 64.77 GB/s for N4quda16WilsonDslashCudaI7double2S1_EE with policy,comm=0000,reconstruct=12,Xpay,topo=1111
PostTune N4quda16WilsonDslashCudaI7double2S1_EE
PreTune N4quda16WilsonDslashCudaI7double2S1_EE
Tuning N4quda16WilsonDslashCudaI7double2S1_EE with policy,comm=0000,reconstruct=12,Xpay,dagger,topo=1111 at vol=6x12x12x4
About to call tunable.apply block=(32,1,1) grid=(1,1,1) shared_bytes=0 aux=(0,0,0)
    block=(32,1,1), shared=0, aux=(0,0,0,0) gives 38.76 Gflop/s, 65.28 GB/s
About to call tunable.apply block=(32,1,1) grid=(1,1,1) shared_bytes=0 aux=(1,0,0)
    block=(32,1,1), shared=0, aux=(1,0,0,0) gives 38.57 Gflop/s, 64.96 GB/s
About to call tunable.apply block=(32,1,1) grid=(1,1,1) shared_bytes=0 aux=(6,0,0)
    block=(32,1,1), shared=0, aux=(6,0,0,0) gives 38.60 Gflop/s, 65.01 GB/s
About to call tunable.apply block=(32,1,1) grid=(1,1,1) shared_bytes=0 aux=(7,0,0)
    block=(32,1,1), shared=0, aux=(7,0,0,0) gives 38.67 Gflop/s, 65.13 GB/s
About to call tunable.apply block=(32,1,1) grid=(1,1,1) shared_bytes=0 aux=(8,0,0)
    block=(32,1,1), shared=0, aux=(8,0,0,0) gives 38.69 Gflop/s, 65.16 GB/s
About to call tunable.apply block=(32,1,1) grid=(1,1,1) shared_bytes=0 aux=(9,0,0)
    block=(32,1,1), shared=0, aux=(9,0,0,0) gives 38.62 Gflop/s, 65.05 GB/s
Tuned block=(32,1,1), shared=0, aux=(0,0,0,0) giving 38.76 Gflop/s, 65.28 GB/s for N4quda16WilsonDslashCudaI7double2S1_EE with policy,comm=0000,reconstruct=12,Xpay,dagger,topo=1111
PostTune N4quda16WilsonDslashCudaI7double2S1_EE
ERROR: Already bound to this texture reference (rank 0, host gt035.clusternet, /home/lmazur/quda/include/texture.h:129 in Texture())
       last kernel called was (name=N4quda16WilsonDslashCudaI7double2S1_EE,volume=6x12x12x4,aux=type=interior,comm=0000,ghost=0000,reconstruct=12,Xpay)
```

This happens only on Fermi cards. On pascal cards it works without issues.. How can I fix this?

with regards,
Lukas

### PR DESCRIPTION
**Pull request by maddyscientist**
Two fixes for multi-GPU Fermi (lazy ghost allocation and zero-copy textures broke with texture references)
* `cudaColorSpinorField::Ghost2()` directly returns required pointers, since `createGhostTextureObject` is not called on Fermi which sets `ghost_field_tex` pointers
* Always rebind spinor textures to ensure correct ghost pointers are used
* Closes #685

### CODE REVIEW

File: include/quda_internal.h [hunk 1]
```diff
@@ -44,6 +44,11 @@
 #define USE_TEXTURE_OBJECTS
 #endif
 
+// if not using texture objects then we need to disable multi-blas support since these don't work with texture references
+#ifndef USE_TEXTURE_OBJECTS
```
Comment (mathiaswagner) [inline include/quda_internal.h]: should this be fixed here or in cmakelists.txt ? No real preference

Comment (maddyscientist) [reply include/quda_internal.h]: I'd say to leave it as is, since this is a short-term fix for Fermi architectures that we will remove once we branch off QUDA 0.9.
